// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9_f6zE165N8ixl5l2wzha_apnOPqP5w',
    appId: '1:949168519770:web:82c00e18d10c6a99903663',
    messagingSenderId: '949168519770',
    projectId: 'brounitystudio-d59af',
    authDomain: 'brounitystudio-d59af.firebaseapp.com',
    databaseURL: 'https://brounitystudio-d59af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brounitystudio-d59af.firebasestorage.app',
    measurementId: 'G-XE0RPHCKW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBNrjmmGtEI2GGm06sbpqrHQz4af2BHM',
    appId: '1:949168519770:android:682ea4bc6f59d8d6903663',
    messagingSenderId: '949168519770',
    projectId: 'brounitystudio-d59af',
    databaseURL: 'https://brounitystudio-d59af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brounitystudio-d59af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4cHRXVNkw5Spb5GvHRuo-y5ApMP0Bvq4',
    appId: '1:949168519770:ios:0e59ea4e3f61ade4903663',
    messagingSenderId: '949168519770',
    projectId: 'brounitystudio-d59af',
    databaseURL: 'https://brounitystudio-d59af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brounitystudio-d59af.firebasestorage.app',
    androidClientId: '949168519770-7vcteas0i8r5kccu4q0eb257lo3himll.apps.googleusercontent.com',
    iosClientId: '949168519770-pt8km120p32cfj0o989s4nbugjq31rp5.apps.googleusercontent.com',
    iosBundleId: 'com.brounitystudio.cicekdoktoru',
  );
}
